[SP-25]-база-знаний-admin-panel
fourSaws/DataLouna pull request #3
Opened 2022-09-15 17:57 UTC by NewAcidRain

2022-09-15 19:27 UTC, artempas reviewed
почитай про on-delete, важно отследить чтобы корректно происходили удаления ключевых слов и связей

2022-09-15 19:27 UTC, artempas commented on server/DataLouna/LounaAdmin/models.py
> +    text = models.CharField(max_length=64, verbose_name='Ключевые слова')
verbose_name должно быть ключевОЕ словО

2022-09-15 19:27 UTC, artempas commented on server/DataLouna/LounaAdmin/models.py
> +    keywords_id = models.ForeignKey('Keywords',on_delete=models.CASCADE,verbose_name='ID Ключевого слова')
on delete не каскад наверное
чтобы при удалении связи не удалялись слова и статьи

2022-09-15 19:27 UTC, artempas commented on server/DataLouna/LounaAdmin/models.py
> +        verbose_name = 'Ключевые слова статей'
ед. число

2022-09-15 19:27 UTC, artempas commented on server/DataLouna/LounaAdmin/views.py
> +def getArticles(request):
naming: getArticle

2022-09-15 19:27 UTC, artempas commented on server/DataLouna/LounaAdmin/views.py
> +                return Response({'getChildren_Error':'ID not found'},status=status.HTTP_400_BAD_REQUEST)
need to test
потому что есть узлы без детей (конечные у которых статьи)

2022-09-16 09:52 UTC, NewAcidRain commented on server/DataLouna/LounaAdmin/views.py
> +                return Response({'getChildren_Error':'ID not found'},status=status.HTTP_400_BAD_REQUEST)
Ты уверен, что выделил правильную область?

2022-09-16 09:52 UTC, NewAcidRain commented on server/DataLouna/LounaAdmin/views.py
> +                return Response({'getChildren_Error':'ID not found'},status=status.HTTP_400_BAD_REQUEST)
> need to test потому что есть узлы без детей (конечные у которых статьи)

Ты уверен что выделил правильную область?

2022-09-16 10:08 UTC, artempas requested changes
перенастроил линтер

2022-09-16 10:15 UTC, closed without merging